### ISSUE TITLE
Tagging the code to cut a release

### ISSUE THREAD

**Issue by antoniovazquezblanco** [Thog/ghidra_falcon#5]
Hi, I am working on a Ghidra extension that is able to install other extensions from Github (https://github.com/antoniovazquezblanco/GhidraExtensionManager).

A while ago I contributed with a pipeline that would generate releases automagically but a tag has never been pushed. For this reason, the pipeline has not generated a "non-prerelease" release with all the artifacts for different Ghidra versions...

It would help me if you could push a tag to make the built extension available for other people.

Thanks

**Comment by marysaka** [comment]
Done, see https://github.com/marysaka/ghidra_falcon/releases/tag/v1.1.
